name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  buildx:
    runs-on: windows-2025
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        use: true
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          name/app
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        use: true
    - name: Build
      run: |
        docker build . -f Dockerfile -t docker.io/${{ secrets.DOCKER_USERNAME }}/maybook
